name: Report generation workflow

on:
  push:
    paths:
      - 'demos/**/logs/faid/**.yml'

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-min.txt

      - name: Extract changed directories
        id: extract_dirs
        run: |
          echo "Extracting changed directories..."
          CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD | grep 'demos/.*/logs/faid/.*.yml' | xargs -n1 dirname | sort -u)
          echo "Changed directories: $CHANGED_DIRS"
          echo "::set-output name=dirs::$CHANGED_DIRS"

      - name: Generate reports for each changed log directory
        run: |
          for dir in ${{ steps.extract_dirs.outputs.dirs }}; do
            echo "Generating report for $dir..."
            cd $dir
            python -c "print('Generating reports for $dir...'); from faid.report import generate_all_reports; generate_all_reports()"
            echo "Report generated successfully for $dir"
          done

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: html-reports
          path: demos/**/reports/